### ISSUE TITLE
BiblioteQ Raspberry Pi OS arm64 build

### ISSUE THREAD

**Issue by yasbean** [textbrowser/biblioteq#102]
Hello!

Would it be possible to build a package for 64 bin Raspberry Pi OS (arm64)?

**Comment by textbrowser** [comment]
Hey, I remember you. There is a build and a bundle. See Releases.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/releases/download/2021.04%2F10/BiblioteQ-2021.04.10_armhf.deb

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/releases/tag/2021.04%2F10

Well, the bundle is for Raspbian. I hope the OS that you're referring to is a Debian-based one. If not, you'll have to install Qt and BQ's requirements and built it on your own.

**Comment by textbrowser** [comment]
sudo apt install ./BiblioteQ-2021.04.10_armhf.deb 
[sudo] password for pi: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'biblioteq' instead of './BiblioteQ-2021.04.10_armhf.deb'
The following additional packages will be installed:
  libpoppler-qt5-1 libpoppler82 libpq5 libqt5sql5-psql libxslt1.1 libyaz5
The following NEW packages will be installed:
  biblioteq libpoppler-qt5-1 libpoppler82 libpq5 libqt5sql5-psql libxslt1.1 libyaz5
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,710 kB/12.4 MB of archives.
After this operation, 7,035 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 /home/pi/BiblioteQ-2021.04.10_armhf.deb biblioteq armhf 2021.04.10 [9,690 kB]
Get:2 http://mirror.sjc02.svwh.net/raspbian/raspbian buster/main armhf libpoppler82 armhf 0.71.0-5 [1,356 kB]
Get:3 http://mirror.sjc02.svwh.net/raspbian/raspbian buster/main armhf libpoppler-qt5-1 armhf 0.71.0-5 [134 kB]
Get:4 http://mirror.sjc02.svwh.net/raspbian/raspbian buster/main armhf libpq5 armhf 11.11-0+deb10u1 [153 kB]
Get:5 http://mirror.sjc02.svwh.net/raspbian/raspbian buster/main armhf libqt5sql5-psql armhf 5.11.3+dfsg1-1+rpi1+deb10u4 [70.0 kB]
Get:6 http://mirror.sjc02.svwh.net/raspbian/raspbian buster/main armhf libxslt1.1 armhf 1.1.32-2.2~deb10u1 [215 kB]
Get:7 http://mirror.sjc02.svwh.net/raspbian/raspbian buster/main armhf libyaz5 armhf 5.27.1-2 [782 kB]
Fetched 2,710 kB in 3s (786 kB/s)
Selecting previously unselected package libpoppler82:armhf.
(Reading database ... 67599 files and directories currently installed.)
Preparing to unpack .../0-libpoppler82_0.71.0-5_armhf.deb ...
Unpacking libpoppler82:armhf (0.71.0-5) ...
Selecting previously unselected package libpoppler-qt5-1:armhf.
Preparing to unpack .../1-libpoppler-qt5-1_0.71.0-5_armhf.deb ...
Unpacking libpoppler-qt5-1:armhf (0.71.0-5) ...
Selecting previously unselected package libpq5:armhf.
Preparing to unpack .../2-libpq5_11.11-0+deb10u1_armhf.deb ...
Unpacking libpq5:armhf (11.11-0+deb10u1) ...
Selecting previously unselected package libqt5sql5-psql:armhf.
Preparing to unpack .../3-libqt5sql5-psql_5.11.3+dfsg1-1+rpi1+deb10u4_armhf.deb ...
Unpacking libqt5sql5-psql:armhf (5.11.3+dfsg1-1+rpi1+deb10u4) ...
Selecting previously unselected package libxslt1.1:armhf.
Preparing to unpack .../4-libxslt1.1_1.1.32-2.2~deb10u1_armhf.deb ...
Unpacking libxslt1.1:armhf (1.1.32-2.2~deb10u1) ...
Selecting previously unselected package libyaz5:armhf.
Preparing to unpack .../5-libyaz5_5.27.1-2_armhf.deb ...
Unpacking libyaz5:armhf (5.27.1-2) ...
Selecting previously unselected package biblioteq.
Preparing to unpack .../6-BiblioteQ-2021.04.10_armhf.deb ...
Unpacking biblioteq (2021.04.10) ...
Setting up libpq5:armhf (11.11-0+deb10u1) ...
Setting up libpoppler82:armhf (0.71.0-5) ...
Setting up libqt5sql5-psql:armhf (5.11.3+dfsg1-1+rpi1+deb10u4) ...
Setting up libxslt1.1:armhf (1.1.32-2.2~deb10u1) ...
Setting up libpoppler-qt5-1:armhf (0.71.0-5) ...
Setting up libyaz5:armhf (5.27.1-2) ...
Setting up biblioteq (2021.04.10) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for mime-support (3.62) ...

**Comment by textbrowser** [comment]
All set? Happy? If not, please re-open this ticket. Closing!

**Comment by textbrowser** [comment]
All set? Happy? If not, please re-open this ticket. Closing!

**Comment by textbrowser** [comment]
There's also a document detailing the process of building your own package. See Documentation/README.RASPIAN.

**Comment by yasbean** [comment]
Of course! Thank you for the wonderful work!

**Comment by textbrowser** [comment]
See https://github.com/textbrowser/biblioteq/blob/master/Documentation/README.RASPBIAN for guidance on creating the DEBIAN file. I can prepare README and control files for arm64 if you'd like. You may need to modify the control file.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/biblioteq/commit/4c70c7f9cc9d893955e01851391fd8df3ba23d56

**Comment by yasbean** [comment]
I successfully built BiblioteQ-2021.05.15_arm64.deb.  The only suggestion I have is to build a link to biblioteq.sh in /us/bin/ or /usr/local/bin .  Since this is a built package, perhaps move everything from /usr/local to /usr.

**Comment by textbrowser** [comment]
Did your build require changes?

**Comment by textbrowser** [comment]
I use /usr/local because the package is not part of the base system. /usr/local is derived from legacy BSD, if I remember correctly. The directory typically contains software built locally.

https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html

/opt is also a possibility.

**Comment by yasbean** [comment]
Actually, my build required no charges.  Your documentation and control file were perfect.  I mostly struggled with getting my system to use Qt5 and not 4.
I am certainly no expert on these things, but I always thought /usr/local is for locally compiled software, but if distributed as a package (.deb, .rpm, etc), and so managed by the system package manager, it goes in /usr.
