### ISSUE TITLE
Large quantity (sqlite migrated) memberid beginning with number

### ISSUE THREAD

**Issue by tamascz** [textbrowser/biblioteq#129]
`DROP USER IF EXISTS 15a15` currently syntax error
so now I cannot delete a member even if i create the login role for him/her.

`DROP USER IF EXISTS "15a15"` could be working.

**Comment by textbrowser** [comment]
I don't understand.

> create user 15a15;

This will be prohibited by PostgreSQL. So, this user cannot exist in PQ.

**Comment by textbrowser** [comment]
Alright, I see. Well, you should not be attempting to bypass PQ validation with the expectation that BQ is aware of the process that was used to bypass PQ.

**Comment by textbrowser** [comment]
When defining a role, define it without special characters. "15a15" is a special input.

**Comment by textbrowser** [comment]
OK, I've modified BQ to attempt to remove roles as follows:

1. Attempt to remove the provided role. For example, "DROP USER IF EXISTS %1".
2. If #1 fails, attempt #3.
3. DROP USER IF EXISTS "%1"

**Comment by textbrowser** [comment]
OK, this was an annoying configuration. I had to remove a validator to test.

I created "15a15" in PQ through BQ. I had to provide the surrounding double quotes. PQ created the user 15a15. In the member table, the user is represented as "15a15". Since the user is "15a15", removing the account from PQ was successful because the user name is already escaped. Thus, I do not need to modify BQ.

If, however, the user is created in PQ using double quotes while double quotes are not used in the member table, the user cannot be removed via BQ. This is not a fault of BQ.

**Comment by textbrowser** [comment]
I suggest that you prepend 'm' to each user identifier in the original data. The import will work. PQ will be happy. Nothing special will be required for DROPs.

**Comment by tamascz** [comment]
Thanks. Unfortunately the memberid's already (imported) in PQ as 15a15 from the sqlite db. When I tried to delete a member, confronted with the known PQ restriction, which causes the syntax error and results in unsuccessful deletion (even if the "dummy" 15a15 user role was created beforehand eg. from pgadmin).

**Comment by textbrowser** [comment]
At the psql prompt:

update member set memberid = '"15a15"' where memberid = '15a15';

Then you'll be able to remove the member using BiblioteQ.
