### ISSUE TITLE
Automatic creation of special copies during importing of books.

### ISSUE THREAD

**Issue by textbrowser** [textbrowser/biblioteq#205]
CSV files may include duplicate ISBNs. If a duplicate ISBN is discovered, assign the entry as a copy. Allow administrators to select (before the import) the designated barcode field.

**Comment by meteos77** [comment]
I tried to do the manual creation of 2 books with the same isbn.

1 - if I want to fill the Multi-Volume Set ISBN field, I have to uncheck the ISBNs box
2 - as soon as the ISBNs box is checked, BiblioteQ asks you to fill in an isbn-10 or isbn-13 field.

Can you remove the Multi-Volume Set ISBN field from this "option" because if it was independent of the checkbox, my duplicate problem would be solved I think.
creation of 2 books with the Multi-Volumes Set ISBN field (not unique) and none of the id and isbn-13 fields (unique) would be filled so no conflict in BiblioteQ.

ps: I don't know if multi-volumes set isbn is part of the id search?

**Comment by textbrowser** [comment]
OK, moved.

Queries do not utilize the field.

**Comment by meteos77** [comment]
thank you very much, the main problem of multi-volumes is now solved.
ex import file : 
[Import-Multivolume.csv](https://github.com/textbrowser/biblioteq/files/8653377/Import-Multivolume.csv)

base obtained :
[2022-05-09-test-multi-volumes.sqlite.zip](https://github.com/textbrowser/biblioteq/files/8653401/2022-05-09-test-multi-volumes.sqlite.zip)

accession_number is available for borrowing and returning

**Comment by textbrowser** [comment]
A new widget is not required.

**Comment by textbrowser** [comment]
Completed the changes. Here is the test CSV file I imported.

[Import-Multivolume.csv](https://github.com/textbrowser/biblioteq/files/8795109/Import-Multivolume.csv)

**Comment by textbrowser** [comment]
Oopsie.
