### ISSUE TITLE
Textcolor / Fieldcolor in MacOS Darkmode

### ISSUE THREAD

**Issue by Infonautic** [textbrowser/biblioteq#272]
Hello,

I'm using the precompiled Version for MacOS, if da Mac enters Darkmode I can't read die Input fields because cell color is light yellow an Textcolor switches from Black to White.
So in Darfmode the text becomes invisible.

I hope you can fix it.
Thank you.

Thomas

Im currently using "BiblioteQ Version 2022.12.25 Architecture __amd64__. Compiled on Dec 24 2022, 08:37:03." 
System is MacMini M1 and MacOS 13.1 Ventura.

**Comment by textbrowser** [comment]
This suggests that two new options are required: mandatory field color, modified field color.

**Comment by textbrowser** [comment]
I will not be distributing build files for Mac, Windows, and Linux in 2023 and beyond. The last release in 2022 is the final release to include such files. You'll need to build your own after the changes.

**Comment by textbrowser** [comment]
Why? I don't have the necessary hardware. Building for diverse platforms is a lost effort. That is, people don't care for my time and energy. It's expensive because I have to consume energy on PowerPC, Mac, several Linuxes, Windows, Android. Also, I find the processes repetitive and boring. I'm not learning new things. I've considered automated the processes, but again, that'd be expensive. Then there are the people who complain that a bundle doesn't work for their system. So, lots of complaining and very little happiness from people. :)

**Comment by Infonautic** [comment]
Uff, i understand this contradiction. After many years of searching for the right software, I finally hoped BiblioteQ is the one.
Postgres - Check, Mac - Check, Vital development - Check. I'm very happy to get my little bookcollection in a database. 
I have great respect of your work an your energy. Compiling works fine for me, but with precompiled Images you get a potential higher user base. I'm not a developer, I'm one of these annoying users. ;-)

Thanks for your work!

**Comment by textbrowser** [comment]
I have PQ working in my Mac test case. However, deploying it does not work because Homebrew. It's a complicated story. I could correct it but my machine is so inadequate: Homebrew has declared it obsolete, Apple has declared it obsolete, building projects is woefully slow, the machine overheats, the machine sometimes reboots without reason. A Mac Mini is $700. Newer laptops are $1000. I don't use Apple and I was once happy to distribute on it out of happiness. Also, I have other interests than building things for unhappy people. :)

**Comment by textbrowser** [comment]
Tickets and queries are pleasant because they're easy and rolling out source releases is performed by GitHub. Quick and easy. I mentioned it elsewhere that a release can take an entire day. Like 8 or more hours.

**Comment by Infonautic** [comment]
we do not have an SLA, take your time, im happy with the Software. But I thought to report a report, is a 1st a report. If you think it is worth then fix it, if not let it be. 
As I wrote i appreciate your work very much. Thank you.

**Comment by textbrowser** [comment]
Completed.

**Comment by pedrorey-cs** [comment]
Hey @textbrowser. What is needed to get Postgres working on macOS?
I'm a huge fan of BiblioteQ but totally not familiar with Qt. Is there anything we could do to help?
Again, I appreciate your work!

**Comment by textbrowser** [comment]
I don't distribute PQ because it was becoming really difficult to create a distribution file without otool. Perhaps that's nicer now. Install Homebrew and the Qt PostgreSQL package. Build BQ using that version of Qt. Should work. If you need a server, that's beyond the question. :) There are many documents covering PQ installation.

**Comment by textbrowser** [comment]
And the June, 2023 release does include files for MacOS, Windows, and a bunch of Linuxes, including PowerPC and Pi

**Comment by textbrowser** [comment]
The official Qt installer will install the PQ plugin. You will need to build the pq library (libpq.dylib) on MacOS and link it accordingly.
