### ISSUE TITLE
Releases after 2023.02.25 do not include binary.

### ISSUE THREAD

**Issue by duhow** [textbrowser/biblioteq#300]
Checking GitHub Releases, `2023.02.25` is the last one to include the binary file inside the assets.

**Comment by textbrowser** [comment]
Please do not request release files. :)

**Comment by textbrowser** [comment]
This is a demanding puzzle without a nice resolution. A BiblioteQ release requires that I spend an entire day, many hours, of unpaid work bundling: ARM, Android, MacOS, PowerPC, Ubuntu, and Windows. Those are 6 release files, sometimes 7. A free alternative does not release. I can: build files on ARM, PowerPC, and Ubuntu autonomously. However, I cannot deploy them easily. Android, Mac, and Windows; cannot. GH does not have a great delivery environment. Doesn't exist anywhere.

So, best build your own version.

Oh, and people complain if I build a Debian file because they do not maintain their operating system. They'd like 18.04, 20.04, 22.04, etc. All LTS versions of Ubuntu and another Debian 9 or 10 or 11.

Impossible amount of expectations.

**Comment by textbrowser** [comment]
Someone also requested a Docker package. Yikes. Not happening.

**Comment by textbrowser** [comment]
Oh, and they want a universal TAR bundle. Or a universal Linux build. They want it all.

**Comment by textbrowser** [comment]
Plus, release notes on GH and in GH releases. Lots of work. The release notes I do not mind. Two places. GH provides the nice source bundle. Package maintenance is a super bore for me.

**Comment by textbrowser** [comment]
I'm working on Qup for simplifying my software releases. Please recommended another open-source software tool for updating software. Please let it be similar to Qup.

https://github.com/textbrowser/qup

**Comment by duhow** [comment]
I am so sorry, but I am not "demanding to be satisfied", I just reported this as an error I saw.

Also, I couldn't find any guide on "how to build" this software and generate a binary.

From your comment may I understand that you have tested GitHub Actions builds but it was not working? If not, I am glad to make a PR to build the binaries automatically, but I need the steps / dependencies list.

**Comment by textbrowser** [comment]
There is a brief COMPILING document in the source. There is also information for Windows. :)

I doubt GH Actions can be used to: create a Mac DMG, a Debian (say Buster) file, or a Raspbian 11 Debian file. Remember, Qt is necessary and a bunch of other libraries. But, if they can, that's wonderful. :)

Thank you for the understanding.

**Comment by textbrowser** [comment]
https://docs.github.com/en/actions/automating-builds-and-tests

I do not see C++ or Qt mentioned there. Perhaps they're implying that only projects written in those languages can be autonomously built or you can create autonomous specifications in the listed languages.

**Comment by textbrowser** [comment]
https://github.com/marketplace?type=actions&query=qt+
https://github.com/marketplace?type=actions&query=c%2B%2B+

**Comment by textbrowser** [comment]
You may spend as much time preparing actions as I spend creating bundles. :)
