### ISSUE TITLE
Custom cell colors.

### ISSUE THREAD

**Issue by textbrowser** [textbrowser/biblioteq#369]
Highlight the main table's cells based on cell and column text. Recommended elsewhere.

**Comment by textbrowser** [comment]
Completed for special queries. A == B must be true. Not A like B. If title is Publisher and search string is VIZ Media, VIZ MEDIA will not be considered.

**Comment by textbrowser** [comment]
A toLower(A) == toLower(B) would work too bust will introduce some delays.

**Comment by textbrowser** [comment]
Or A.contains(B). It gets super slow super fast with so many options.

**Comment by meteos77** [comment]
Bravo, for me this will be the feature of the year!
Future enhancements look great to me.

An improvement if possible in the display of the result: have a column in the first position that indicates "an exclamation mark" for example to indicate that a cell of the table presents a positive result to the filters (if the column is not displayed because it's too far to the right).

**Comment by meteos77** [comment]
Of course, by using this feature we accept the slowdown in the display of the result. But since it's an option... everyone can choose between speed and function.

**Comment by textbrowser** [comment]
> Bravo, for me this will be the feature of the year! Future enhancements look great to me.
> 
> An improvement if possible in the display of the result: have a column in the first position that indicates "an exclamation mark" for example to indicate that a cell of the table presents a positive result to the filters (if the column is not displayed because it's too far to the right).

I cannot add columns which indicate the state of other columns.

**Comment by textbrowser** [comment]
Aha, you'd like a system which informs you of the filtered results. Like, item I was highlighted. Becomes worrisome here and we should not concern ourselves with such instances. Say you have five configured items resulting in 200 highlighted cells. A perhaps message in the status bar. But what is noise? It gathers stardust and we perish in stimulation.

**Comment by textbrowser** [comment]
I dislike Android with Samsung's events notifications. Although I request that it not notify me, it persistently notifies me of things that are irrelevant. I smash the phone. This is persistent nonsense.

**Comment by meteos77** [comment]
I've solved my problem with a Custom Query. We can sort the columns as we like, so that the filtered column appears first.

For the prefabricated columns ... you have to scroll up and down to see the colored cell ... not very practical.

 Suggestion: would you consider putting the text of a line with a filtered cell in bold or italic as noise?

I like silence
