### ISSUE TITLE
How to install on windows?

### ISSUE THREAD

**Issue by zjDrummond** [textbrowser/biblioteq#372]
I'd like to give the software a try, but I don't see a windows installer in the releases. I saw a windows portable mention in the features section though. Are there plans to release the app for windows? Thanks.

**Comment by textbrowser** [comment]
Yah I don't have a machine to create the ZIP-y file for Windows. I did but the machine died and Windows is expensive and so is new computer. You is own your own good luck Instructions are available in the source tree. And an installer is not required. Everything in the ZIP-y. Perhaps I'll build it on a friend's computer or not. Don't know. Source is free so you're 89%.

**Comment by textbrowser** [comment]
Yes very portable but if I don't have the money to buy computers and people donate like essentially $1 per year, well, the expectation that I buy hardware to give already-free software is bonkers. I'm not an oligarch and if I were, BQ would be un-free.

**Comment by textbrowser** [comment]
And is not just BQ been asked on other projects too. Hey, where is for Windows? You say it in your notes is for Windows. And sometimes they scream and are offended. I ain't saying you are offended or screaming, but the dream costs money and without support we all gots to do ourselves the work. So I'm like, OK. Have to wait or learn to build on you own. Easy!

**Comment by textbrowser** [comment]
Mentioning the components requires that I keep that document alive. Sometimes Qt remove components and sometimes they're renamed and sometimes Qt 5 becomes Qt 6 becomes Qt 7 and 9. So, not pragmatic for me because I don't consider that aspect helpful. If someone is dedicated and clever, they'll discover the things they need. Now, before I'm abashed with regrets and isms, many creators and designers and volunteers give people free and good stuff. Good? Free? Well, we want more. So anyway, when I don't want to consider and think, I download a previous and new Windows ZIP-y and look through the library names and then guess the products in the Qt installer. I don't install the entire Qt because like BQ doesn't need WebEngine and purchasing etc.

**Comment by textbrowser** [comment]
Will try to have a Windows program this week.

**Comment by textbrowser** [comment]
> Thank you for the responses. I'm always grateful for whatever is available for an open source project. I don't mind learning how to build for windows. I did find the pdf listed in a few releases ago, and started to follow those instructions. I was unclear on what parts of Qt to install though. I saw that the full Qt install was like 48 gigabytes. I can't really afford to leave that installed. Can I install it, build the installer, and then uninstall it?

In the ZIP-y you shall find the dependencies of BQ from Qt and some other ones which Qt needs. So you can build and uninstall if you but you will need the dependencies otherwise BQ will not live.

**Comment by MossyQuill** [comment]
For what parts of Qt to install--I went through the process of installing on Windows recently so I may be able to help. If you get to the part of the installer that has different boxes with install options, look for one that mentions MinGW and pick that one. Don't choose the custom install.

**Comment by textbrowser** [comment]
Building now. Closing ticket.

**Comment by textbrowser** [comment]
Up.
