### ISSUE TITLE
TLS initialization error on Windows.

### ISSUE THREAD

**Issue by JSchue** [textbrowser/biblioteq#374]
When opening a https for download of information from and SRU-server of for cover images a network error occurs.

![Screenshot 2024-08-15 180558](https://github.com/user-attachments/assets/52b869fe-d684-4ad9-95e5-fb1ceaee385d)
Biblioteq version: 2024.06.30
Windows 11

The error is not shown under Ubuntu Linux for the same version of Bibliteq.

**Comment by textbrowser** [comment]
And why is TLS required? SRU in biblioteq.conf is HTTP for LoC.

**Comment by textbrowser** [comment]
Please post the SRU server you're communicating with.

**Comment by JSchue** [comment]
I'm using the the SRU-werver of the german national library DNB with following lines in biblioteq.conf:
<
[SRU DNB]

name = Deutsche Nationalbiblithek
proxy_host =
proxy_password =
proxy_port =
proxy_type = None
proxy_username =
url_isbn = "https://services.dnb.de/sru/dnb?version=1.1&operation=searchRetrieve&query=num%3D%1 or num%3D%2&recordSchema=MARC21-xml&startRecord=1&maximumRecords=1"
url_issn = "https://services.dnb.de/sru/zdb?version=1.1&operation=searchRetrieve&query=num%3D%1&recordSchema=MARC21-xml&startRecord=1&maximumRecords=100"
>

and I get the same error when I try to get cover images from OpneLibrary (or nay other  source I tried) as well.

**Comment by textbrowser** [comment]
Added SRU entry to biblioteq.conf.

**Comment by textbrowser** [comment]
The query completes correctly on Linux.

**Comment by JSchue** [comment]
Yes, I know. It seems to be an issue with https connection under windows as OpenLibrary query gives the same error.

**Comment by textbrowser** [comment]
I'll test Windows whenever I can.

**Comment by meteos77** [comment]
Biblioteq version:  github today

If it helps: test on VM windows 10.
I also get the same SRU French message.

**Comment by textbrowser** [comment]
Is not a concern because I would try the non-HTTPS and drop Windows for something else. Like FreeBSD or MacOS or even the award-winning Kubuntu. You don't need Windows because it's an advertising platform which records everything for the Mother Land of Gates-ville. Seriously aside, it may be a missing library or a missing method or your particular version of Windows. I don't work on Windows and the last free virtual machine I installed failed and become dead after a Windows update so I dropped it because it was zombied and I don't prefer zombies. Some people do, I don't. They kind of rot and smell and eat brains but maybe some people enjoy zombie friends I don't know.

**Comment by textbrowser** [comment]
Newer Windows after Windows 3.1 and after Windows 98 and sometimes after a release included a Windows TLS other than the OpenSSL most likely or likely or some variation of likely derived from OpenSSL. It's a proprietary system so we have to guess or read or someone leaked information about their security layer and so anyway, it is different because you can query Qt and it'll inform you about it and when I did, the string is weird. Like, this is TLS version A and that's ll you need to know. So good luck? More later.

**Comment by textbrowser** [comment]
And now onto the fascinating world of Windows. It amazes me, not spectacularly nor fashionably, that a trillion-dollar company cannot and will not produce meaningful reports whenever software failures occur. They are first a software company. Their errors are meaningless. Imagine you query a person, a non-weird person, regarding the time of day. You have an idea that they time is before sunset and after sunrise because you're on Earth and it's light. The person responds 0x0102030405 and dies. Immediately.

**Comment by textbrowser** [comment]
Download tls directory from https://github.com/textbrowser/qt-products/tree/main/6.5_LTS/Windows/plugins and place in the plugins folder. The tls directory should be plugins/tls. Or download attachment and place unzipped in plugins.

[tls.zip](https://github.com/user-attachments/files/17063762/tls.zip)

**Comment by meteos77** [comment]
With the 3 additional files, it works fine. Thanks for the fix

**Comment by textbrowser** [comment]
Is so splendid when so much detail exists. Like reading nonsense that no one ever reads but exists for those who like to read in bright futures and meaning. Is like waking up in a garden and falling into the thorns of raspberries. Bad but so tasty.

**Comment by JSchue** [comment]
Thank you for your great support. 
It works now.
This is another example that support for Open Source software is working better than for most commercial software. 
Unfortunately all I could give back to the community is a qualified description of the problem.

**Comment by textbrowser** [comment]
I don't know about that. Open Source works when there is love. Like, a pet loves you because you feed it and because it is fond of you. You're the big daddy or mommy and there is a relationship. Maybe it's parasitic or maybe it's symbiosis.

Proprietary anything requires a monetary transaction. Might exist some help from the holder because it is beneficial to them that they appear to be interested in helping you. That's where it stops. There ain't no discussions about merit, quality, beliefs, and idea of a gentler world.

It's all about the money, the profit, and the dependency you have on them. It's kind of like fascism without it being forced on you, well, unless you can't find something else. You're either with Windows or you can't compute. Oh, and you have to pay too. It certainly is a political power thingy.

We cats believe that you don't have to find BQ. But we love it. We mean, after like decades of purring, something's there beyond theory.

See you.
