### ISSUE TITLE
Report : Import CSV and ? button.

### ISSUE THREAD

**Issue by meteos77** [textbrowser/biblioteq#385]
I noticed that the question mark "?" in the import csv interface for BQ to detect column names in the csv file.

There is a confusion in the field "multivolume_set_isbn column" : BQ detects it as an "id".

Can you modify this detection ? 

Thank you in advance for improving BQ.

**Comment by textbrowser** [comment]
Some words are subsets of other words and enumerating all permutations is not my interest. These are permutations because the order of their discovery is also important. Multi-volume contains volume and volume_set contains volume so both should be the multi-like column and not the volume-like column. I'm not going to list every subset of every subset.

**Comment by meteos77** [comment]
Ok I understand it was to let you know if you hadn't detected it. if it's a technical problem ... no problem.

**Comment by textbrowser** [comment]
The word date is present in 5 columns. Which is the desired one is context and if the context is broken, BQ doesn't know which one is good for you. And you know what else? You can select the one you want.

**Comment by textbrowser** [comment]
It's not that I didn't look for it, it's that I don't want to do this work when you can select it.

**Comment by meteos77** [comment]
I have no doubt that you're looking for the best for BQ, always within the constraints of Interest / Time / Difficulty.
