### ISSUE TITLE
Returning books requests / questions.

### ISSUE THREAD

**Issue by jerzyPL** [textbrowser/biblioteq#70]
So, here are my requests/questions:
* can you add the option to change/customize the order of viewable columns?
* can you add the option of (constant) resizing the width of viewable columns?
(the present option ‘Automatically Resize Column Widths’ causes that visible on the screen is only a very long book title, and disabling this option causes that some headers [e.g. header ‘Place of Publication’ after clicking/selecting a book all the headers are becoming in bold, & in addition some terms in Polish which are longer than in English] simply do not fit);
* maybe, I say maybe, a good option would be to automatically assign the 'Accession Number'?
* I have, also, the impression that the function of returning reserved books is somewhat "hidden" in 'Modify Book Entry' => 'Item Reservation Status'...
(I expected this feature to be found where I borrowed the book, i.e. in 'Members Browser' => 'Reserve Selected Item').
I would be grateful if you would devote your attention to the above issues.

Finally, a small suggestion: what would you say to the following rearrangement for the ‘Create Book Entry’ window (and, eventually, for the other windows)?
The guiding idea was simplicity and transparency, as well as the ability to fit everything on the display screen without scrolling…
![add book browser](https://user-images.githubusercontent.com/66644295/84578259-0e19f980-adc4-11ea-811b-f332f0fdbe6a.jpg)

**Comment by textbrowser** [comment]
1. You can drag-and-drop the columns manually. However, the final configurations are not retained after the application is terminated. It may be a lot of work retaining the current values because the column orders are linked with the database queries.

2. More information is needed. What's a constant resize? I could add a default size per column, per category. Also a lot of work. So, in Other Options, each column per each category could have a default width which can be modified by the user.

3. What's a default, suitable Accession Number that everyone would find acceptable?

4. See All Reserved category. This category lists all reserved items. A new option within this category would allow reserved items to be returned without having to access their detailed views. A separate addition is to include the reserved items in the Members Browser.

5. Will look.

I will not be able to address these requests for the July release.

**Comment by textbrowser** [comment]
4. Note that it's possible to change the Due Date of a reserved item via the current implementation.

**Comment by textbrowser** [comment]
These are nice requests to be considered. :)

**Comment by jerzyPL** [comment]
Ad 1: Just as I thought: database settings.
Ad 2. Constant/permanent i.e. those, as you have wrote above, which "are retained after the application is terminated".
"Other Option" - that sounds logical and has potential.
Ad 3. As for me: a sequence number.
Ad 4. OK.
Ad 5. ;-)
Haste makes waste...

**Comment by textbrowser** [comment]
Automatic accession values will be available in the July release. :)

**Comment by jerzyPL** [comment]
Great news! Thank you.
BTW: I am wondering, who uses the "Back Cover Image" option?...
Maybe, it would be better to "sacrifice" this option and the space saved in the "Add Item" panel use for something else?

**Comment by textbrowser** [comment]
I love options. Options everywhere and for everyone. Lots of colors too. More options, more configuration, more joy.

Two important options that would be helpful: configurable layout and configurable options. A living application.

**Comment by jerzyPL** [comment]
And who will develop all these options? 🤔

**Comment by textbrowser** [comment]
People with time.

**Comment by textbrowser** [comment]
New sequences (PostgreSQL + SQLite) added!

**Comment by textbrowser** [comment]
Next release will feature the requested book layout.

**Comment by jerzyPL** [comment]
Thank you. So 2020.09.09 will be the great day...

**Comment by textbrowser** [comment]
I suppose. :)

**Comment by textbrowser** [comment]
![Screenshot_20200904_205732](https://user-images.githubusercontent.com/10701156/92293408-4f1c3880-eef1-11ea-9473-524835d9a738.png)

**Comment by jerzyPL** [comment]
Wow! You made it so it looks better now than I expected. Respect, and thank you :-)

**Comment by textbrowser** [comment]
:)

**Comment by jerzyPL** [comment]
At the eleventh hour: Maybe it would be better to swap "Location" and "Price" so that "Price" is under "Monetary Units"?
![92293408-4f1c3880-eef1-11ea-9473-524835d9a738](https://user-images.githubusercontent.com/66644295/92470379-9860d680-f1d6-11ea-97c9-e84dc918d76a.png)

**Comment by textbrowser** [comment]
Sure. Made the change.

**Comment by jerzyPL** [comment]
Thank you.

**Comment by textbrowser** [comment]
Boo. Reviewing the return item request. So, you'd like to return items in the general view. That is, from All Reserved.

**Comment by jerzyPL** [comment]
Yes, the "Reservation Status..." is located in "Modify Book Entry" and only there is the option "Return".
But in the "View" > "Categories" > "All reserved" we have (I don't know why?) the option "Reserve selected item...", which always returns with "Error...", because it is impossible to reserve an item already reserved...
Maybe, instead of "Reserve selected item...", there should be exactly the "Return" option?
Similarly, why there is the option "Delete selected item(s)", which always returns with "Error..."?
And why there is option to "Duplicate" or/and "Modify" selected item(s), which is/are already reserved?

**Comment by textbrowser** [comment]
1. An item may have multiple copies. So, it's perfectly logical to reserve an item while in Reserve Selected Item.
2. Duplicating an item does not duplicate its status. This is similar to copy-and-paste.
3. You're allowed to remove an item if it's not reserved. The state is inspected during the delete process.
4. You're allowed to modify items which are reserved. Discretion falls upon the owner of the data.

Remember, BQ supports PQ. As such, the items in the table may be different from the items in the database. This can also occur with SQLite (multiple instances of BQ accessing the same SQLite file). BQ cannot display the actual state of the database in real-time. By also allowing actions in categories where the actions may seem inappropriate for some operators, there is flexibility for others which prefer a very open environment. That is, allow me to do almost anything.

**Comment by textbrowser** [comment]
There are database transactions whenever data changes occur; multiple users cannot harm the data consistency. Of course, this cannot prevent one operator from overwriting another. Total locks would be intolerable.

**Comment by jerzyPL** [comment]
OK. I understand, but I disagree.
You're approaching this whole point on the scale of a large library: dozens of employees enter data for various items, other dozen borrow books... The database is constantly changing etc... OK.
I come back to the essential point:
- the presence of the "Return" option only in "Add / Modify Item Entry" requires searching for items in the general database (in the case of my library: 25.000 items);
- why not add it in a natural place, i.e. in "Reserved Items" (in the case of my library: 5 items)...

**Comment by textbrowser** [comment]
See my comment from yesterday. :P I asked if that is what you wanted and that's the process that I'll introduce: simplify return process by adding it to the All Reserved category.

**Comment by jerzyPL** [comment]
100%.

**Comment by textbrowser** [comment]
> See my comment from yesterday. :P I asked if that is what you wanted and that's the process that I'll introduce: simplify return process by adding it to the All Reserved category.

I will try to complete this for the January release. Sorry for the delay!

**Comment by jerzyPL** [comment]
Thank you!
_Patience is the key to paradise..._ :)

**Comment by textbrowser** [comment]
Indeed.

**Comment by meteos77** [comment]
Witaj jerzyPL i najlepsze życzenia na ten rok 2022. ( (tłumaczenie maszynowe może zawierać nonsensy)

Hello jerzyPL and best wishes for this year 2022.

I would like to start an experience sharing dialogue with you about managing a library with BiblioteQ.

According to the date of the ticket, you have been using it for at least 1.5 years.
my library (French, run by volunteers; no professionals) is looking for a simple and user-friendly software that meets the needs of a library of our size (about 10,000 items - almost all books).

if you want to answer my request, create a new thread
entitled "sharing experiences with BiblioteQ" because I don't want to waste the ticket
return documents.

once again, happy new year and take care of yourself
Sincerely


Witaj jerzyPL i najlepsze życzenia na ten rok 2022.

Chciałabym rozpocząć z Państwem rozmowę na temat zarządzania biblioteką z BiblioteQ.

Zgodnie z datą na bilecie, używasz go od co najmniej 1,5 roku.
Szukam prostego i przyjaznego dla użytkownika oprogramowania, które spełniałoby potrzeby biblioteki naszej wielkości (około 10 000 dokumentów - prawie same książki).

jeśli chciałbyś odpowiedzieć na moją prośbę, utwórz nowy wątek
zatytułowany "dzielenie się doświadczeniami z BiblioteQ", ponieważ nie chcę zmarnować
dokumenty zwrotne.

jeszcze raz, szczęśliwego nowego roku i dbaj o siebie
Z poważaniem

**Comment by meteos77** [comment]
regarding the return of a document

I suggest : 
Fxx key (Return a Document function)
fields (accession_number) (scan handheld or enter number)
it is finished.

variant
search document in the table (by accession_number or by id or by title) already in place
right button 
return document
it's over

remains the case of duplicate documents (but with an access_number normally no worries)

**Comment by textbrowser** [comment]
> regarding the return of a document
> 
> I suggest : Fxx key (Return a Document function) fields (accession_number) (scan handheld or enter number) it is finished. allows the management of return by batch
> 
> variant search document in the table (by accession_number or by id or by title) already in place right button return document it's over
> 
> variant through the members window as suggested by jerzyPL display the list of members select user display his list of borrowed documents (multi-selection of documents is available) right button return document(s) or a back button finish
> 
> remains the case of duplicate documents (but with an access_number normally no worries)

The third variant is already possible save for the missing batch return function. :) This is the most elegant solution as one usually returns the items of an individual.

**Comment by meteos77** [comment]
I'm waiting for JerzyPL's opinion with no doubt other practical cases


for the borrowing of a document, it is necessary to make the connection between the document and a borrower.

but for the returns it is not in my opinion linked to a member but to the return of the document itself in the library: from the point of view of the BiblioteQ machine, it will manage well by itself :-) and that makes some clicks of gained!

at our place : cases of returns encountered

case 1 : m1 returns X Y Z documents that he had borrowed then it's OK with your method. this can be used to make a point with the member : you have 2 books left at home ...

case 2 : m1 had borrowed 10 documents A B C D E F N O P V ; m2 child of m1 10 documents G H I J K L M Q R S ; 1 month later m1 returns the 20 documents : A B C D E F G H I J K L M O P Q R V S.

variant case 2: m2 returns 10 books that they lent to each other with his brother m3 and do not know who borrowed which documents.
=> it is by the number of the document that you will return the documents in the most efficient way.

case 3 : some libraries provide boxes for returning books to allow readers to return them outside of opening hours and therefore there is no one there.
=> it is by the number of the document that you will return these documents.

![box-800x422](https://user-images.githubusercontent.com/56431039/148522776-74d8681c-6370-4e28-b993-c345c7ad45c9.jpg)







other case by the absurd: m1 dies it is a stranger of the library who returns the books by putting them in front of the door: it is well the notion of the return which is important not which makes the action

**Comment by textbrowser** [comment]
> Thank you! _Patience is the key to paradise..._ :)

Group returns is completed. The All Reserved category displays the hang-up telephone. Once activated, the selected items are marked as being returned. The individual return functionality remains. So now there are two methods for returning items.

**Comment by textbrowser** [comment]
> I'm waiting for JerzyPL's opinion with no doubt other practical cases
> 
> for the borrowing of a document, it is necessary to make the connection between the document and a borrower.
> 
> but for the returns it is not in my opinion linked to a member but to the return of the document itself in the library: from the point of view of the BiblioteQ machine, it will manage well by itself :-) and that makes some clicks of gained!
> 
> at our place : cases of returns encountered
> 
> case 1 : m1 returns X Y Z documents that he had borrowed then it's OK with your method. this can be used to make a point with the member : you have 2 books left at home ...
> 
> case 2 : m1 had borrowed 10 documents A B C D E F N O P V ; m2 child of m1 10 documents G H I J K L M Q R S ; 1 month later m1 returns the 20 documents : A B C D E F G H I J K L M O P Q R V S.
> 
> variant case 2: m2 returns 10 books that they lent to each other with his brother m3 and do not know who borrowed which documents. => it is by the number of the document that you will return the documents in the most efficient way.
> 
> case 3 : some libraries provide boxes for returning books to allow readers to return them outside of opening hours and therefore there is no one there. => it is by the number of the document that you will return these documents.
> 
> ![box-800x422](https://user-images.githubusercontent.com/56431039/148522776-74d8681c-6370-4e28-b993-c345c7ad45c9.jpg)
> 
> other case by the absurd: m1 dies it is a stranger of the library who returns the books by putting them in front of the door: it is well the notion of the return which is important not which makes the action

A library or a farm or any entity with patrons has members. When a member borrows an item, there's a transaction recorded. However the item is returned is not important. The completion of the transaction is. So that's what I meant that there is a relationship between the borrowed item and the borrower and that relationship is in the form of a database record. :) BQ does not generate transaction identifiers. The borrowed item has three attributes: its identifier, the copy's identifier, and the member's identifier. Those three are unique for any item and a patron. The place the item on the virtual shelf, the three identifiers are required. But the patron is not required to return the item. Their identifier is.

**Comment by textbrowser** [comment]
The old form of returning items was complicated: the item had to be discovered, its details opened, its copy editor opened, the copy selected, and a confirmation. In All Reserved, the correct items can be selected because the items should be physically present during their return. Or, listing a member's items via the Members Browser. Three methods.

**Comment by textbrowser** [comment]
The 4th item in the original request is completed.
