### ISSUE TITLE
multiple clients for DB

### ISSUE THREAD

**Issue by andrkac** [textbrowser/biblioteq#79]
A question about instance with PostgreSQL - May I connect few clients for one DB (on another machine) - at the same time?
Now it works with sqlite and I don't have postgresql on my server, but I can install it.

I would have web AND desktop client of such catalogue, but I understand that this is not the target of Biblioteq. Using DB together with my wife on separate systems must be enough :)

**Comment by textbrowser** [comment]
New page added to the document.

BQ targets small institutions, large institutions, and private users. PQ is essentially limit-less. So, yes, you can connect multiple instances of BQ to a single database server. As BQ uses transactions, data remains consistent. Of course, BQ does not automatically respond to changes which occur on a database, however, it does include database-level protections which prevent duplicates, unauthorized removal, unauthorized modifications, etc. BQ also includes parameterized queries in order to decrease SQL injections. PQ includes all sorts of mechanisms to keep your data safe. So read up on it.
