### ISSUE TITLE
Use the BiblioteQ as a manager collection

### ISSUE THREAD

**Issue by nikolay-litvin** [textbrowser/biblioteq#81]
Thanks for good app)
I use the Biblioteq for create catalog my ebook library. But now I can only attach ebooks to the collection, but then my file quickly increasing. Can I simple add a path to pdf or ePub books?

**Comment by textbrowser** [comment]
BQ prefers to contain the files as file paths are not reliable. If you're concerned with a large SQLite file, consider installing and using PostgreSQL. BQ supports it.

I will add an option to compress the attachments. Perhaps that will help.

**Comment by textbrowser** [comment]
See https://www.sqlite.org/limits.htm.

Maximum Database Size

Every database consists of one or more "pages". Within a single database, every page is the same size, but different database can have page sizes that are powers of two between 512 and 65536, inclusive. The maximum size of a database file is 4294967294 pages. At the maximum page size of 65536 bytes, this translates into a maximum database size of approximately 1.4e+14 bytes (281 terabytes, or 256 tebibytes, or 281474 gigabytes or 256,000 gibibytes).

This particular upper bound is untested since the developers do not have access to hardware capable of reaching this limit. However, tests do verify that SQLite behaves correctly and sanely when a database reaches the maximum file size of the underlying filesystem (which is usually much less than the maximum theoretical database size) and when a database is unable to grow due to disk space exhaustion.

**Comment by textbrowser** [comment]
For books, grey literature, and magazines, compression is already included.

**Comment by textbrowser** [comment]
Closing because compression is applied.
